### ISSUE TITLE
"Giving up due to no left retries. Wrong credentials?" occurs again

### ISSUE THREAD

**Issue by 01ste02** [Ekman/home-assistant-pure-i9#99]
I am using v2.0.2 of the integration, and since about 15:00 Stockholm time, it has stopped working. Have Electrolux changed their API again?

```
2024-12-29 21:12:08.452 ERROR (SyncWorker_2) [purei9_unofficial.util] Giving up due to no left retries. Wrong credentials?
2024-12-29 21:12:08.525 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry **REDACTED** for purei9
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/util.py", line 22, in do_http
    r.raise_for_status()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.ocp.electrolux.one/one-account-authorization/api/v1/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/util.py", line 22, in do_http
    r.raise_for_status()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.ocp.electrolux.one/one-account-authorization/api/v1/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/purei9/__init__.py", line 17, in async_setup_entry
    robots = await hass.async_add_executor_job(purei9_client.getRobots)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/cloudv3.py", line 276, in getRobots
    r = do_http("GET", self.apiurl + "/appliances", headers=self._getHeaders())
                                                            ~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/cloudv3.py", line 250, in _getHeaders
    r = do_http("POST", self.authorizationurl + "/token", json={
        "clientId": self.client_id,
    ...<4 lines>...
        "User-Agent": self.user_agent
    })
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/util.py", line 26, in do_http
    return do_http(method, url, retries-1, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/util.py", line 26, in do_http
    return do_http(method, url, retries-1, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/util.py", line 29, in do_http
    raise r
  File "/usr/local/lib/python3.13/site-packages/purei9_unofficial/util.py", line 22, in do_http
    r.raise_for_status()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error:  for url: https://api.ocp.electrolux.one/one-account-authorization/api/v1/token
```

**Comment by 01ste02** [comment]
Seems to have been a temporary issue where I might have been rate-limited from their api due to frequent restarts. Issue does not persist and is not reproducable after a couple of days.
